image: node:latest

cache:
  paths:
    - node_modules/
    
build:
    before_script:
        - npm install
    script:
        - npm run build

test:
  before_script:
        - npm install
  script:
    - npm run test