GET http://localhost:3000/api/friendLists/

###

GET http://localhost:3000/api/friendLists/5dc5cc3e7b4e9c3e979ad7ac

###

POST http://localhost:3000/api/friendLists
content-type: application/json

{
    "friendList": [1,2],
    "friendRequests": [1]
}